baseURL = "https://nikhilkumar123789.github.io/theinfiniteblog1729/"
languageCode = "en-us"
title = "The Infinite Line"
theme = "hyde"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Essential for MathJax

[params]
  description = "A blog about mathematics and its applications"